spring:
  application:
    name: store
  datasource:
    url: jdbc:sqlserver://RAKEYSH_REDDY:1433;databaseName=storedb;encrypt=true;trustServerCertificate=true
    username: springuser
    password: Spring@7897
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    locations: classpath:db/migration
  main:
    banner-mode: "off"

logging:
  level:
    root: ERROR
    org.springframework: ERROR
    org.springframework.boot: ERROR
    org.hibernate: ERROR
    org.flywaydb: ERROR
  pattern:
    console: "%msg%n"
